### ISSUE TITLE
backtrack, node dash.js crashes after trying to load first page.

### ISSUE THREAD

**Issue by rabbitear** [infosec-au/bugbountydash#2]
node dash.js crashes on me with this backtrace:
```
node dash.js
TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (/home/userone/dev/GIT/bugbountydash/node_modules/cheerio/lib/parse.js:55:25)                                                                
    at module.exports (/home/userone/dev/GIT/bugbountydash/node_modules/cheerio/lib/
parse.js:17:11)                                                                         
    at Function.exports.load (/home/userone/dev/GIT/bugbountydash/node_modules/cheerio/lib/static.js:19:14)                                                                 
    at /home/kreator/dev/GIT/bugbountydash/dash.js:287:25
    at Request.handleRequestResponse [as _callback] (/home/userone/dev/GIT/bugbounty
dash/node_modules/unirest/index.js:461:25)                                              
    at Request.self.callback (/home/userone/dev/GIT/bugbountydash/node_modules/unirest/node_modules/request/request.js:373:22)                                              
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/userone/dev/GIT/bugbountydash/node_modules/unirest
/node_modules/request/request.js:1318:14)                                               
    at emitOne (events.js:101:20)
```
Running node 6.10.1 on Linux.
Let me know if you want more information on this, I'm not sure where to start to try to fix this myself.

**Comment by Rockcena** [comment]
I got like same issue 

```
TypeError: Cannot read property 'program' of undefined
    at /Users/bb/Desktop/bugbountydash/dash.js:271:57
    at Request.handleRequestResponse [as _callback] (/Users/bb/Desktop/bugbountydash/node_modules/unirest/index.js:461:25)
    at Request.self.callback (/Users/bb/Desktop/bugbountydash/node_modules/unirest/node_modules/request/request.js:373:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/bb/Desktop/bugbountydash/node_modules/unirest/node_modules/request/request.js:1318:14)
    at emitOne (events.js:120:20)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/bb/Desktop/bugbountydash/node_modules/unirest/node_modules/request/request.js:1266:12)
    at emitNone (events.js:110:20)

```
node v8.2.1 on Mac

**Comment by abdilahrf** [comment]
yes same issue with me :/

**Comment by timothyleung** [comment]
It seems like the way they fetch BC username handle is not valid anymore. A simple fix will be just replacing 
 ` // save bugcrowd username for later
                bcuserhandle = $("span.profile strong").text()
` 
to 
` // save bugcrowd username for later
                bcuserhandle = "yourusername"
`

**Comment by abdilahrf** [comment]
you can use this solution too `bcuserhandle = $("nav>a>strong").text()`
